variables:
  GIT_STRATEGY: clone

stages:
  - dependencies
  - build_and_test

install:
  stage: dependencies
  script:
    - npm install --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  only:
    refs:
      - merge_requests
    changes:
      - package-lock.json

build_app:
  stage: build_and_test
  script:
    - chmod +x ng
    - ./ng build --prod
  artifacts:
    name: "angular-app-pipeline"
    paths:
      - dist/awesome-app
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull





#  cache:
#    key:
#      files:
#        - yarn.lock
#    paths:
#      - node_modules
#    policy: pull
